In [1]:
my_list = [1,2,3]

In [1]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
mat = np.array(my_mat)

In [10]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,11, 2) 
#start from 0 and go to 10, the third term is the step size

array([ 0,  2,  4,  6,  8, 10])

In [36]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))
# we define the size of the matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones(19)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

In [22]:
np.linspace(0,5,100)
# the first item is start the second is the end and the third item is
# the number of items between start and end

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [24]:
np.eye(4) #creating identity matrix with dimension of the item

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(5) # random numbers between 0 and 1

array([0.53991286, 0.35608638, 0.95613297, 0.50408019, 0.24486587])

In [30]:
np.random.rand(4,5)

array([[0.62372513, 0.93683166, 0.05903639, 0.1450193 , 0.69786832],
       [0.96207088, 0.16522726, 0.65975766, 0.11241149, 0.75163619],
       [0.80797485, 0.74164404, 0.0306198 , 0.27332061, 0.82291682],
       [0.77353862, 0.06071969, 0.96255533, 0.7079145 , 0.29887413]])

In [33]:
np.random.randn(2) 
# two random numbers from the standard normal distribution

array([-0.2436303 ,  0.57291997])

In [34]:
np.random.randn(4,4) 

array([[ 0.20630781, -0.01256704, -2.16706339,  0.65504379],
       [ 0.28385544,  0.96638756,  0.74299433, -0.835616  ],
       [ 0.40117247, -0.68868405, -0.1164385 ,  1.18797786],
       [-0.44912938, -0.21212999,  0.59737961, -1.78092402]])

In [38]:
np.random.randint(1,100, 10)
# gives random number between the given range, 
#the third item is the number of items in array

array([56, 28, 74, 36,  5, 70, 17,  2, 83, 82])

In [39]:
arr = np.arange(25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
renarr = np.random.randint(0,50,10)

In [42]:
renarr

array([42, 38, 47, 12, 27, 13, 37, 40, 29, 43])

In [44]:
arr.reshape(5,5) #reshapes the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
renarr

array([42, 38, 47, 12, 27, 13, 37, 40, 29, 43])

In [46]:
renarr.max()

47

In [47]:
renarr.min()

12

In [48]:
renarr

array([42, 38, 47, 12, 27, 13, 37, 40, 29, 43])

In [49]:
# how to find the location of max and min value in the array

In [51]:
renarr.argmax() # gives the location of the max number

2

In [55]:
renarr.argmin() # gives the location of the min number

3

In [61]:
arr = arr.reshape(5,5)

In [62]:
arr.shape

(5, 5)

In [63]:
arr.dtype

dtype('int32')

In [64]:
from numpy.random import randint

In [66]:
randint(2,10)

4

In [69]:
#NUMPY ARRAY INDEXING

In [71]:
arr = np.arange(0,11)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr[8]

8

In [74]:
arr[1:5]

array([1, 2, 3, 4])

In [75]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [76]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [77]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [80]:
arr[0:5] = 100 # all items in the range are equaled to the set number

In [81]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [82]:
arr = np.arange(0,11)

In [83]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
slice_of_arr = arr[0:6]

In [86]:
slice_of_arr[:] = 99

In [88]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [89]:
arr_copy = arr.copy()

In [90]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [91]:
arr_copy[:] = 100

In [92]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [93]:
#2d arrays

In [95]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [96]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [97]:
arr_2d[0][0]

5

In [98]:
arr_2d[0]

array([ 5, 10, 15])

In [100]:
arr_2d[2,1] # single comma notation 

40

In [102]:
arr_2d[:2,1:] #take all to the third row and from the first column

array([[10, 15],
       [25, 30]])

In [103]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [105]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [106]:
arr = np.arange(1,11)

In [107]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
bool_arr = arr > 5

In [110]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [112]:
arr[bool_arr] # returns only the numbers which are true

array([ 6,  7,  8,  9, 10])

In [113]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [116]:
arr[arr<3]

array([1, 2])

In [117]:
arr_2d = np.arange(50).reshape(5,10)

In [118]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [120]:
arr_2d[2:4,1:5]

array([[21, 22, 23, 24],
       [31, 32, 33, 34]])

In [2]:
# NUMPY operations

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])